services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: smart_home
      POSTGRES_USER: smart_home
      POSTGRES_DB: smart_home
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d smart_home -U smart_home" ]
      interval: 10s
      timeout: 10s
  smart-home-server:
    image: e154/smart-home-server-test:latest
    environment:
      PG_USER: smart_home
      PG_PASS: smart_home
    stdin_open: true
    volumes:
      - /Users/delta54/smart-home/conf
      - /Users/delta54/smart-home/data
      - /Users/delta54/smart-home/snapshots
    tty: true
    links:
      - postgres:postgres
    ports:
      - "3001:3001"
      - "3002:3002"
      - "1883:1883"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    links:
      - smart-home-server:smart-home-server
    volumes:
      - /Users/delta54/smart-home/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8081:8080
    environment:
      - TZ=Asia/Bangkok
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyUSB0
volumes:
  db-data:
